# Usa una imagen base de Python
FROM python:3.13.3

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios
COPY . .

# Instala las dependencias
RUN pip install --no-cache-dir flask flask-cors

# Expone el puerto en el que Flask corre
EXPOSE 5000

# Comando para correr la app
CMD ["python", "app.py"]
